sonar.projectKey=Thais-PH_portfolio_23107d23-3ac0-46cd-9532-bc7452932398
sonar.sources=app
sonar.tests=__tests__
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/*.test.tsx,**/layout.tsx,**/*.d.ts,next.config.js,postcss.config.js,tailwind.config.ts,jest.config.ts,jest.setup.ts
